### ISSUE TITLE
Better heuristic to guess declare-const vs assert

### ISSUE THREAD

**Issue by Lysxia** [wenkokke/schmitty#43]
Right now unused variables are treated as assertions, e.g., this fails:

```
_ : (x y : ℤ) → x ≤ x  -- Unrecognized identifier Agda.Builtin.Int.Int in script "(assert Agda.Builtin.Int.Int)"
```

Maybe a better heuristic is to try decoding every element both as a sort and as a term and pick whichever succeeds. It would also be useful to just drop uninterpretable assumptions, so that you can use `solveZ3` deep in a term with a lot of junk in the context.

It doesn't seem straightforward to do this at the moment because of the current architecture that produces a `RawScript` at a stage where the theory-specific decoding functions aren't available.

**Comment by wenkokke** [comment]
I'm currently overhauling the library, so: what change do you think would need to happen for this to be fixed easily?

**Comment by Lysxia** [comment]
Sure, I'm happy to work on this. I would merge `reflectToRawScript` (in `SMT.Theory.Raw.Reflection`) and `checkRawScript` (in `SMT.Script.Reflection`) into a single function. Or do you see any issues with that approach?

**Comment by wenkokke** [comment]
> Maybe a better heuristic is to try decoding every element both as a sort and as a term and pick whichever succeeds.

This seems like it would run into some serious complexity issue?

**Comment by wenkokke** [comment]
> Sure, I'm happy to work on this. I would merge `reflectToRawScript` (in `SMT.Theory.Raw.Reflection`) and `checkRawScript` (in `SMT.Script.Reflection`) into a single function. Or do you see any issues with that approach?

I'd prefer to keep these separate, but I admit that currently `checkRawScript` is only used to check the scripts coming from reflected terms.

**Comment by wenkokke** [comment]
> It would also be useful to just drop uninterpretable assumptions, so that you can use solveZ3 deep in a term with a lot of junk in the context.

It should be possible to drop uninterpretable assumptions in `reflectToRawScript`, unless I'm misunderstanding what you mean by "uninterpretable"?

**Comment by Lysxia** [comment]
I mean to decide whether a term represents a sort or a statement based on whichever of `checkSort` or `checkRawTerm` in `SMT.Script.Reflection` succeeds, whereas now this decision is made in `reflectToRawScript` which doesn't have a `theory` in scope. I can think of two ways of doing this:

1. change the result type of `reflectToRawScript` to `Rfl.Term` or some similar representation that doesn't commit to interpret an Agda type as either a sort or a statement;
2. parameterize `reflectToRawScript` by a `theory` so that `checkSort` and `checkRawTerm` can be implemented in it. But then it didn't seem that `checkRawScript` was doing much more work beyond applying those two functions, so I thought I might as well fuse everything.

**Comment by wenkokke** [comment]
I think I'm convinced that merging the two functions is a good idea.
